class CustomError(ValueError):
    pass


class PersonNotFound(CustomError):
    pass
